[package]
name = "files-watcher"
version = "0.0.0"
publish = false
edition = "2024"

# Docker file has `RUN cargo fetch`. We don't pass src folder so Dockerfile has error:
# ```
# error: failed to parse manifest at `/app/Cargo.toml`
# Caused by:
#   no targets specified in the manifest
#   either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
# ```
#
# Secion `[[bin]]` makes everything fine
[[bin]]
name = "files-watcher"
path = "src/main.rs"

[dependencies]
notify-debouncer-full = { version = "0.7.0", default-features = false }

[profile.release]
# Code size optimization (replaces default -O3)
opt-level = "z"
# Enables Link-Time Optimization (removes unused code from dependencies)
lto = true
# Decrease parallel build but improve optimization of binary
codegen-units = 1
# Disable stack unwinding
panic = "abort"
# Delete debug symbols and import table
strip = true
